apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: {{ .Values.namespace }}
  labels:
    app: backend
data:
  DB_HOST: {{ .Values.database.config.host | default "postgres-service" | quote }}
  DB_PORT: {{ .Values.database.config.port | default "5432" | quote }}
  DB_NAME: {{ .Values.database.config.name | quote }}
  DB_USER: {{ .Values.database.config.user | quote }}
